services:
  api-service:
    container_name: identity-api-container
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge