server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://host.docker.internal:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:tuan6326}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: @spring.profiles.active@

  jwt:
    signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
    valid-duration: 3600 # in second
    refreshable-duration: 36000 # in seconds
