server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: tuan6326
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "NsMbalb1tpOXCAghdPR93q7E5fGoDaggLIqvogcdywm3kxVhEiZxeURHEenf8il8"
